# frozen_string_literal: true

# FactorySeeder Seeds
# This file is automatically generated by FactorySeeder

FactorySeeder.generate do |seeder|
  # Example: Create 10 users with admin trait
  # seeder.create(:user, count: 10, traits: [:admin])

  # Example: Create posts with associations
  # seeder.create_with_associations(:post, count: 5, associations: {
  #   author: { factory: :user, count: 1 },
  #   comments: { factory: :comment, count: 3 }
  # })
end
