name: Release gem

on:
  push:
    tags:
      - 'v*'

jobs:
  push:
    name: Build and push gem to RubyGems
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Release gem
        uses: rubygems/release-gem@v1
