# frozen_string_literal: true

require 'thor'

module FactorySeeder
  class CLI < Thor
    class_option :verbose, type: :boolean, aliases: '-v', desc: 'Enable verbose output'

    desc 'generate [FACTORY]', 'Generate seeds for a specific factory'
    option :count, type: :numeric, default: 1, desc: 'Number of records to create'
    option :traits, type: :array, desc: 'Traits to apply'
    option :strategy, type: :string, default: 'create', desc: 'Factory strategy (create, build, etc.)'
    option :attributes, type: :hash, desc: 'Additional attributes'
    def generate(factory_name = nil)
      if factory_name
        generate_single_factory(factory_name)
      else
        interactive_generate
      end
    end

    desc 'list', 'List all available factories'
    option :verbose, type: :boolean, aliases: '-v'
    def list
      FactorySeeder.configuration.verbose = options[:verbose] if options[:verbose]

      # Utiliser list_factory_names pour éviter les problèmes de chargement
      factory_names = FactorySeeder.list_factory_names

      if factory_names.empty?
        puts '❌ No factories found. Make sure you have FactoryBot factories in spec/factories/ or test/factories/'
        return
      end

      puts "📋 Found #{factory_names.count} factories:\n\n"

      factory_names.each do |name|
        puts "🏭 #{name}"
      end
    end

    desc 'preview FACTORY_NAME', 'Preview factory data without creating records'
    option :count, type: :numeric, default: 1, aliases: '-c'
    option :traits, type: :string, aliases: '-t'
    option :attributes, type: :string, aliases: '-a'
    def preview(factory_name)
      FactorySeeder.configuration.verbose = true

      # Vérifier si la factory existe
      factory_names = FactorySeeder.list_factory_names
      unless factory_names.include?(factory_name)
        puts "❌ Factory '#{factory_name}' not found"
        puts "Available factories: #{factory_names.first(10).join(', ')}"
        return
      end

      traits = options[:traits]&.split(',')&.map(&:strip) || []
      attributes = parse_attributes(options[:attributes])

      generator = SeedGenerator.new
      preview_data = generator.preview(factory_name, options[:count], traits, attributes)

      puts "🔍 Preview for #{factory_name}:"
      puts JSON.pretty_generate(preview_data)
    end

    desc 'web', 'Start web interface'
    option :port, type: :numeric, default: 4567, aliases: '-p'
    option :host, type: :string, default: 'localhost', aliases: '-h'
    def web
      puts "🌐 Starting FactorySeeder web interface on http://#{options[:host]}:#{options[:port]}"
      puts 'Press Ctrl+C to stop'

      WebInterface.set :port, options[:port]
      WebInterface.set :bind, options[:host]
      WebInterface.run!
    end

    desc 'init', 'Initialize FactorySeeder configuration'
    def init
      puts '🚀 Initializing FactorySeeder...'

      seeds_file = Rails.root.join('db/seeds_factory_seeder.rb')
      unless File.exist?(seeds_file)
        File.write(seeds_file, <<~RUBY)
          # FactorySeeder Seeds
          # This file is automatically generated by FactorySeeder

          FactorySeeder.generate do |seeder|
            # Add your custom seeds here
          end
        RUBY
        puts "✅ Seeds file created: #{seeds_file}"
      end

      initializer_file = Rails.root.join('config/initializers/factory_seeder.rb')
      unless File.exist?(initializer_file)
        File.write(initializer_file, <<~RUBY)
          # frozen_string_literal: true
          # FactorySeeder initializer
          # This file is generated by FactorySeeder

          FactorySeeder.configure do |config|
            config.factory_paths << Rails.root.join('spec/factories').to_s if Dir.exist?('spec/factories')
            config.factory_paths << Rails.root.join('test/factories').to_s if Dir.exist?('test/factories')
            config.verbose = true
          end

          # Load custom seeds so they are available at boot
          seeds_file = Rails.root.join('db/seeds_factory_seeder.rb')
          load seeds_file if File.exist?(seeds_file)
        RUBY

        puts "✅ Initializer created: #{initializer_file}"
      end

      puts '✅ FactorySeeder initialized!'
      puts "  Factory paths: #{FactorySeeder.configuration.factory_paths.join(', ')}"
      puts "  Verbose mode: #{FactorySeeder.configuration.verbose}"
    end


    desc 'seeds [SEED_NAME]', 'Run seeds from db/seeds_factory_seeder.rb'
    option :list, type: :boolean, default: false, desc: 'List all available seeds'
    option :all, type: :boolean, default: false, desc: 'Run all defined seeds'
    option :dry_run, type: :boolean, default: false, desc: 'Preview what would be generated'
    def seeds(seed_name = nil)
      seeds_file = 'db/seeds_factory_seeder.rb'
      
      unless File.exist?(seeds_file)
        puts "❌ Seeds file not found: #{seeds_file}"
        puts "💡 Run 'factory_seeder init' to create the default seeds file"
        return
      end

      # Charger le fichier de seeds pour avoir accès aux seeds définis
      load seeds_file

      if options[:list]
        list_available_seeds
        return
      end

      if options[:all]
        run_all_seeds
        return
      end

      if seed_name.nil?
        puts "❌ Please specify a seed name, use --list to see available seeds, or --all to run all seeds"
        puts "💡 Example: factory_seeder seeds development"
        return
      end

      run_specific_seed(seed_name)
    end

    private

    def list_available_seeds
      # Créer un générateur temporaire pour lister les seeds
      generator = SeedGenerator.new
      
      # Charger le fichier de seeds pour avoir accès aux seeds définis
      load 'db/seeds_factory_seeder.rb'
      
      seeds = generator.list_seeds
      
      if seeds.empty?
        puts "❌ No seeds defined in db/seeds_factory_seeder.rb"
        puts "�� Add seeds using seeder.define_seed :name do ... end"
        return
      end
    
      puts "🌱 Available seeds from db/seeds_factory_seeder.rb:\n\n"
      seeds.each do |seed_name|
        puts "  • #{seed_name}"
      end
      
      puts "\n💡 Run: factory_seeder seeds SEED_NAME"
      puts "💡 Example: factory_seeder seeds development"
      puts "💡 Run all: factory_seeder seeds --all"
    end
    
    def run_all_seeds
      puts "🌱 Running all seeds from db/seeds_factory_seeder.rb"
      
      if options[:dry_run]
        puts "🔍 DRY RUN MODE - No records will be created"
      end
    
      begin
        generator = SeedGenerator.new
        generator.run_all_seeds
        puts "✅ All seeds executed successfully"
      rescue StandardError => e
        puts "❌ Error running seeds: #{e.message}"
        puts e.backtrace.first(5).join("\n") if options[:verbose]
      end
    end
    
    def run_specific_seed(seed_name)
      puts "🌱 Running seed: #{seed_name}"
      
      if options[:dry_run]
        puts "🔍 DRY RUN MODE - No records will be created"
      end
    
      begin
        generator = SeedGenerator.new
        
        # Charger le fichier de seeds pour avoir accès aux seeds définis
        load 'db/seeds_factory_seeder.rb'
        
        unless generator.has_seed?(seed_name)
          puts "❌ Seed '#{seed_name}' not found"
          puts "💡 Available seeds: #{generator.list_seeds.join(', ')}"
          return
        end
    
        generator.run_seed(seed_name)
        puts "✅ Seed '#{seed_name}' executed successfully"
      rescue StandardError => e
        puts "❌ Error running seed '#{seed_name}': #{e.message}"
        puts e.backtrace.first(5).join("\n") if options[:verbose]
      end
    end

    def interactive_generate
      factory_names = FactorySeeder.list_factory_names

      if factory_names.empty?
        puts '❌ No factories found'
        return
      end

      puts '🏭 Available factories:'
      factory_names.each_with_index do |name, index|
        puts "  #{index + 1}. #{name}"
      end

      print "\nSelect factory (number or name): "
      selection = STDIN.gets.chomp

      factory_name = if selection.match?(/^\d+$/)
                       index = selection.to_i - 1
                       factory_names[index]
                     else
                       selection
                     end

      unless factory_name && factory_names.include?(factory_name)
        puts '❌ Invalid selection'
        return
      end

      generate_single_factory(factory_name)
    end

    def generate_single_factory(factory_name)
      # Vérifier si la factory existe
      factory_names = FactorySeeder.list_factory_names
      unless factory_names.include?(factory_name)
        puts "❌ Factory '#{factory_name}' not found"
        return
      end

      traits = options[:traits] || []
      attributes = options[:attributes] || {}

      generator = SeedGenerator.new
      result = generator.generate(factory_name, options[:count], traits, attributes, options[:strategy])

      puts "✅ Generated #{result[:count]} #{factory_name} records"
      puts "Strategy: #{result[:strategy]}"
      puts "Traits: #{traits.join(', ')}" if traits.any?
      puts "Attributes: #{attributes}" if attributes.any?
    end

    def parse_attributes(attributes_string)
      return {} unless attributes_string

      attributes = {}
      attributes_string.split(',').each do |pair|
        key, value = pair.split('=').map(&:strip)
        attributes[key] = value if key && value
      end
      attributes
    end
  end
end
